#!/usr/bin/env bash
set -euo pipefail

# Credits to: https://github.com/debxp/dmenu-scripts/blob/master/dmenu-kill-process
# Replace your launcher in the $launcher variable eg. rofi -dmenu or dmenu

prompt="-p Path:"
root_path="$HOME"
launcher="wofi --dmenu"
file_manager="thunar"

find_path="$(find $root_path -maxdepth 3 -type d | \
             sed 's|^'$root_path/'||' | \
             $launcher -i $prompt )"

if [[ ! -z "$find_path" ]]; then
    $file_manager "$find_path"
fi

exit 0
