#!/bin/sh
set -euox pipefail

LAUNCHER="$(awk -F '=' '/material-launcher/ {print $2}' $HOME/.config/material/config)"
[[ $(echo $LAUNCHER | xargs) == "rofi" ]] && LAUNCHER="rofi -config ~/.config/rofi/config_no-icons.rasi -dmenu " || LAUNCHER="$LAUNCHER --dmenu" # patch for rofi

function run_submenu() {
    "$MENU_SCRIPT"
}

MENU_PATH="/home/${USER}/.config/wofi/manager/submenus"
SUBMENU_TYPE="${1:-"main"}"

# use --cache-file /dev/null to use predefined order
SUBMENU="$(sed '/^### ENTRIES ###$/d' ${MENU_PATH}/${SUBMENU_TYPE}/#entries# | $LAUNCHER -p "~ Material settings ~ " -i)"
MENU_NAME="$(echo $SUBMENU | awk '{sub(/^[^ ]+ /, ""); print}' | xargs)"
MENU_SCRIPT="$MENU_PATH/$SUBMENU_TYPE/$MENU_NAME"

if [[ ! -f "$MENU_SCRIPT" ]]; then
    echo "Error: Script with the name '$MENU_SCRIPT' not found in the specified directory."
    exit 1
fi

run_submenu
