#!/bin/sh
set -euox pipefail

#LAUNCHER="wofi --cache-file /dev/null"
LAUNCHER="fuzzel"

function change_wallpaper() {
	CHANGE_WALLPAPER="/home/${USER}/.config/swww/scripts/change_wallpaper"
	$CHANGE_WALLPAPER $WALLPAPER
}

SWWW_DIR="/home/${USER}/.config/swww"
CURRENT_RICE="$(awk '/rice-current/ {print $NF}' /home/${USER}/.config/material/config)"
WALLPAPER_NAME=$(dir -1 /home/${USER}/.config/swww/walls/${CURRENT_RICE} | $LAUNCHER --dmenu -p "~ Material wallpaper selector ~" -i)
WALLPAPER="/home/${USER}/.config/swww/walls/${CURRENT_RICE}/${WALLPAPER_NAME}"

if [[ ! -f "$WALLPAPER" ]]; then
    echo "Error: Wallpaper file with the name '$WALLPAPER_NAME' not found in the specified directory."
    exit 1
fi

change_wallpaper
