#!/bin/sh
set -euo pipefail

function change_rice() {
	CHANGE_RICE="/home/${USER}/.config/swww/scripts/change_theme"
	$CHANGE_RICE $RICE_NAME
}

function create_name() {
	NAME_FILE="/home/${USER}/.config/swww/current/rice"
	if [[ ! -f "$NAME_FILE" ]]; then
		touch "$NAME_FILE"
	fi

	# empty the file for new text
	echo -n > $NAME_FILE
	echo "$RICE_FULL_NAME" > $NAME_FILE
}

# use --cache-file /dev/null to use predefined order
RICE_SEL_NAME=$(sed '/^### ENTRIES ###$/d' /home/${USER}/.config/swww/rices/#entries# | wofi -p "~ Material rice selector ~" --cache-file /dev/null --dmenu -i) 
RICE_FULL_NAME="$(echo $RICE_SEL_NAME | awk '{sub(/^[^ ]+ /, ""); print}' | xargs)"
RICE_FILE="/home/${USER}/.config/swww/rices/${RICE_FULL_NAME}"
RICE_NAME="$(cat "$RICE_FILE")"

if [[ ! -f "$RICE_FILE" ]]; then
    echo "Error: Rice file with the name '$RICE_FULL_NAME' not found in the specified directory."
    exit 1
fi

create_name
change_rice

