#!/usr/bin/env bash
set -euox pipefail

# Credits to: https://github.com/debxp/dmenu-scripts/blob/master/dmenu-kill-process
# Replace your launcher in the $launcher variable eg. rofi -dmenu or dmenu

#launcher="wofi --dmenu"
launcher="fuzzel --dmenu"
prompt="-p Manual:"

# terminal to open manual
terminal="kitty"

# list all manuals
manual="$(man -k . | $launcher $prompt | awk '{print $1}')"

# open selected manual with terminal
if [[ ! -z "$manual" ]]; then
    eval "$($terminal sh -c "man $manual")"
fi

exit 0
