#!/bin/sh
set -euox pipefail

function change_rice() {
	CHANGE_RICE="/home/${USER}/.config/swww/scripts/change_theme"
	$CHANGE_RICE $RICE_FULL_NAME
}

# use --cache-file /dev/null to use predefined order
RICE_SEL_NAME=$(sed '/^### ENTRIES ###$/d' /home/${USER}/.config/swww/rices/#entries# | wofi -p "~ Material rice selector ~" --cache-file /dev/null --dmenu -i) 
RICE_FULL_NAME="$(echo $RICE_SEL_NAME | awk '{sub(/^[^ ]+ /, ""); print}' | xargs)"
RICE_FILE="/home/${USER}/.config/swww/rices/${RICE_FULL_NAME}"

if [[ ! -f "$RICE_FILE" ]]; then
    echo "Error: Rice file with the name '$RICE_FULL_NAME' not found in the specified directory."
    exit 1
fi

# save the config
sed -i 's|rice-current.*|rice-current = '${RICE_FULL_NAME}'|' ~/.config/material/config
change_rice
