#!/usr/bin/env bash
set -euox pipefail

# Credits to: https://github.com/debxp/dmenu-scripts/blob/master/dmenu-kill-process
# Replace your launcher in the $launcher variable eg. rofi -dmenu or dmenu

launcher="wofi --dmenu"

selected="$(ps -a -u $USER | \
            $launcher -i -p "Type to search and select process to kill" | \
            awk '{print $1" "$4}')"; 

if [[ ! -z $selected ]]; then

    answer="$(echo -e "Yes\nNo" | \
            $launcher -i -p "$selected will be killed, are you sure?")"

    if [[ $answer == "Yes" ]]; then
        selpid="$(awk '{print $1}' <<< $selected)"; 
        kill -9 $selpid
    fi
fi

exit 0
