#!/usr/bin/env bash
set -euox pipefail

# Credits to: https://github.com/debxp/dmenu-scripts/blob/master/dmenu-kill-process
# Replace your launcher in the $launcher variable eg. rofi -dmenu or dmenu

# Check if wofi is already running
if pgrep -x "wofi" >/dev/null; then
    pkill -x "wofi"
    exit 0
fi

script_path="$HOME/.config/wofi/scripts"

#launcher="wofi --dmenu"
launcher="fuzzel --dmenu"

# list only executable non-binary files
run_wofi="$(find $script_path/wofi-* -maxdepth 1 -type f -executable \
          -exec grep -Iq . {} \; -print \
          | sed 's|^'$script_path/'||' \
          | sort \
          | $launcher -i --prompt "~ Material scripts ~")"

eval "$script_path/$run_wofi"

exit 0
