#!/bin/sh

LAUNCHER=$(awk -F '=' '/material-launcher/ {print $2}' $HOME/.config/material/config)
[[ $(echo $LAUNCHER | xargs) == "rofi" ]] && LAUNCHER="rofi -config ~/.config/rofi/config_no-icons.rasi -dmenu " || LAUNCHER="$LAUNCHER --dmenu" # patch for rofi

THEME=$(dir -1 $HOME/.config/material/themes | $LAUNCHER -i -p "~ Delete your preferred theme ~")
CHOICE=$(dir -1 $HOME/.config/wofi/manager/submenus/thememanager/confirm | $LAUNCHER --dmenu -i -p "Theme '$THEME' will be deleted permantly, are you sure?")

[[ "$CHOICE" == "Yes" ]] && rm -f $HOME/.config/material/themes/$THEME
