#!/bin/sh

LAUNCHER=$(awk -F '=' '/material-launcher/ {print $2}' $HOME/.config/material/config)
[[ $(echo $LAUNCHER | xargs) == "rofi" ]] && LAUNCHER="rofi -config ~/.config/rofi/config_no-icons.rasi -dmenu " || LAUNCHER="$LAUNCHER --dmenu" # patch for rofi

THEME=$(dir -1 $HOME/.config/material/themes | $LAUNCHER -i -p "~ Load your preferred theme ~")
~/.config/hypr/scripts/load-config-material ~/.config/material/themes/$THEME 
