#!/bin/sh

LAUNCHER=$(awk -F '=' '/material-launcher/ {print $2}' $HOME/.config/material/config)
[[ $(echo $LAUNCHER | xargs) == "rofi" ]] && LAUNCHER="rofi -config ~/.config/rofi/config_no-icons.rasi -dmenu " || LAUNCHER="$LAUNCHER --dmenu" # patch for rofi

NAME=$(dir -1 $HOME/.config/material/themes | $LAUNCHER -i -p "Enter name for your saved theme: ")
CHOICE=$(dir -1 $HOME/.config/wofi/manager/submenus/thememanager/confirm | $LAUNCHER --dmenu -i -p "Save current theme with name: '$NAME'")

if [[ "$CHOICE" == "Yes" ]]; then
    cp $HOME/.config/material/config $HOME/.config/material/themes/$NAME
    sed -i 's|^config-current.*|config-current = '$(basename $HOME/.config/material/themes/$NAME)'|' $HOME/.config/material/themes/$NAME
    sed -i 's|^config-current.*|config-current = '$(basename $HOME/.config/material/themes/$NAME)'|' $HOME/.config/material/config
fi
