#!/bin/sh

rm -r ../configs/.config # really fucking dangerous operation
mkdir -pv ../configs/.config
mkdir -pv ../configs/.icons/default
    
cp -rvf ~/.config/autoclicker    ../configs/.config/
cp -rvf ~/.config/swaylock       ../configs/.config/
cp -rvf ~/.config/wlogout        ../configs/.config/
cp -rvf ~/.config/gtk-3.0        ../configs/.config/
cp -rvf ~/.config/swww           ../configs/.config/
cp -rvf ~/.config/swaylock       ../configs/.config/
cp -rvf ~/.config/mako           ../configs/.config/
cp -rvf ~/.config/wofi           ../configs/.config/
cp -rvf ~/.config/hypr           ../configs/.config/
cp -rvf ~/.config/waybar         ../configs/.config/
cp -rvf ~/.config/alacritty      ../configs/.config/
cp -rvf ~/.config/neofetch       ../configs/.config/
cp -rvf ~/.config/dunst          ../configs/.config/
cp -rvf ~/.config/kitty          ../configs/.config/
cp -rvf ~/.config/cava           ../configs/.config/
cp -rvf ~/.config/xsettingsd     ../configs/.config/
cp -rvf ~/.bashrc                ../configs/
cp -rvf ~/.gtkrc-2.0             ../configs/
cp -rvf ~/.icons/default/index.theme ../configs/.icons/default/
cp -rvf ~/.tmux.conf             ../configs/
cp -rvf ~/.bin ../configs/
# nice
