#!/bin/sh

cp -rvf ../.config/swaylock      ~/.config
cp -rvf ../.config/wlogout       ~/.config
cp -rvf ../.config/swaylock      ~/.config
cp -rvf ../.config/mako          ~/.config
cp -rvf ../.config/wofi          ~/.config
cp -rvf ../.config/autoclicker   ~/.config
cp -rvf ../.config/gtk-3.0       ~/.config
cp -rvf ../.config/hypr          ~/.config
cp -rvf ../.config/swww          ~/.config
cp -rvf ../.config/waybar        ~/.config
cp -rvf ../.config/alacritty     ~/.config
cp -rvf ../.config/polybar       ~/.config
cp -rvf ../.config/dunst         ~/.config
cp -rvf ../.config/neofetch      ~/.config
cp -rvf ../.config/kitty         ~/.config
cp -rvf ../.config/cava          ~/.config
cp -rvf ../.tmux.conf            ~
cp -rvf ../.bashrc               ~
cp -rvf ../.Xmodmap              ~
cp -rvf ../.xinitrc              ~

chmod +x ~/.config/i3blocks/scripts *
# nice
