#!/bin/sh

sed -i 's|gaps_in.*|gaps_in = 5| ' ~/.config/hypr/hyprland.conf
sed -i 's|gaps_out.*|gaps_out = 15| ' ~/.config/hypr/hyprland.conf
sed -i 's|gaps-in.*|gaps-in = 5| ' ~/.config/material/config
sed -i 's|gaps-out.*|gaps-out = 15| ' ~/.config/material/config

hyprctl reload
