[Desktop Entry]
Type=X-GNOME-Metatheme
Name=Solarized-Light
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=Solarized-Light
GtkTheme=Solarized-Light
IconTheme=Solarized-Light
MetacityTheme=Solarized-Light
