#!/bin/sh

# Set variables for script through rice configs
CURRENT_RICE=${1:-$(awk '/rice-current/ {print $NF}' "${HOME}/.config/material/config" | xargs)}
CURRENT_BG=${2:-$(awk '/wallpaper/ {print $NF}' "${HOME}/.config/swww/rices/${CURRENT_RICE}" | xargs)} # make manual wallpapers possible
MODE=$(awk '/system-theme/ {print $NF}' "${HOME}/.config/swww/rices/${CURRENT_RICE}" | xargs)
CURRENT_ICONS="${3:-$(awk '/icons/ {print $NF}' "${HOME}/.config/swww/rices/${CURRENT_RICE}" | xargs)}"

# Set all variables in the config file
sed -i 's|^rice-current.*|rice-current = '${CURRENT_RICE}'|' ~/.config/material/config # set theme in config before using it as a variable in this script
sed -i 's|^system-theme.*|system-theme = '${MODE}'|' ~/.config/material/config # set theme in config before using it as a variable in this script
sed -i 's|wallpaper-current.*|wallpaper-current = '${CURRENT_BG}'|' ~/.config/material/config

# Launch into perltone if enabled
PERLTONE_STATUS=$(awk '/perltone-status/ {print $NF}' "${HOME}/.config/material/config" | xargs)
PERLTONE_OVERRIDE=$(awk '/perltone/ {print $NF}' "${HOME}/.config/swww/rices/${CURRENT_RICE}" | xargs)

if [[ "$(echo $PERLTONE_STATUS | xargs)" == "on" || "$(echo $PERLTONE_OVERRIDE | xargs)" == "force" ]]; then
    sed -i 's|^perltone-status.*|perltone-status = on|' ~/.config/material/config # set forced perltone on before continuing
    WARNING_STATUS=$(awk '/perltone-warn-on-mono/ {print $NF}' $HOME/.config/material/config | xargs)
    if [[ "$WARNING_STATUS" == "on" && "$COLOR_PALETTE" == "mono" ]]; then 
        dunstify "Material" "Warning! Perltone on monochrome themes may not look good, consider disabling Perltone for them." --timeout=7001
    fi

    $HOME/.config/swww/scripts/change_theme_perltone &
    exit 127
fi

# Generated blurred background first since it takes a while
$HOME/.config/hypr/scripts/swww-wallpaper-blur "$CURRENT_RICE" "$CURRENT_BG" &

# Tmux
sed -i 's|^set -g status-bg.*|set -g status-bg '$([[ "$MODE" == "light" ]] && echo "white" || echo "black" )'|' $HOME/.tmux.conf

# Dunst
sed -i 's|background.*|'"$(sed -n '1p' $HOME/.config/dunst/themes/${CURRENT_RICE})"'|' $HOME/.config/dunst/dunstrc
sed -i 's|foreground.*|'"$(sed -n '2p' $HOME/.config/dunst/themes/${CURRENT_RICE})"'|' $HOME/.config/dunst/dunstrc
sed -i 's|frame_color.*|'"$(sed -n '3p' $HOME/.config/dunst/themes/${CURRENT_RICE})"'|' $HOME/.config/dunst/dunstrc
pkill -x dunst
dunst & disown # reload

# Cava
for ((I=1; I<8; I++)); do
    sed -i 's|^gradient_color_'$I'.*|'"$(sed -n ''$I'p' $HOME/.config/cava/themes/${CURRENT_RICE})"'|' ~/.config/cava/config
done
pkill -SIGUSR2 cava

# Kvantum
kvantummanager --set ${CURRENT_RICE}

# qt5ct 
sed -i "s|^color_scheme_path=.*|color_scheme_path=$HOME/.config/qt5ct/colors/${CURRENT_RICE}.conf|" $HOME/.config/qt5ct/qt5ct.conf
sed -i "s|^icon_theme=.*|icon_theme=${CURRENT_ICONS}|" $HOME/.config/qt5ct/qt5ct.conf

# qt6ct
sed -i "s|^color_scheme_path=.*|color_scheme_path=$HOME/.config/qt6ct/colors/${CURRENT_RICE}.conf|" $HOME/.config/qt6ct/qt6ct.conf
sed -i "s|^icon_theme=.*|icon_theme=${CURRENT_ICONS}|" $HOME/.config/qt6ct/qt6ct.conf

# gtk3
sed -i 's|^gtk-theme-name.*|gtk-theme-name='${CURRENT_RICE}'|' ~/.config/gtk-3.0/settings.ini

# gtk4
rm -rf ~/.config/gtk-4.0
ln -s ~/.local/share/themes/${CURRENT_RICE}/gtk-4.0 ~/.config/gtk-4.0

# flatpak gtk
flatpak --user override --env=GTK_THEME="${CURRENT_RICE}" # flatpak gtk is not intended to work, and very hacky not all apps will work with this
flatpak --user override --env=ICON_THEME="${CURRENT_ICONS}"

# Kitty
ln -sf ~/.config/kitty/themes/${CURRENT_RICE}.conf ~/.config/kitty/themes/theme.conf 
pkill -SIGUSR1 kitty # reload

# Wlogout
ln -sf ~/.config/wlogout/themes/${CURRENT_RICE}.css ~/.config/wlogout/themes/theme.css

# Waybar
ln -sf ~/.config/waybar/themes/${CURRENT_RICE}.css ~/.config/waybar/themes/theme.css
~/.config/hypr/scripts/manage-waybar & # reload

# Rofi
ln -sf $HOME/.config/rofi/themes/${CURRENT_RICE}.rasi $HOME/.config/rofi/themes/theme.rasi

# Hyprland
ln -sf ~/.config/hypr/themes/${CURRENT_RICE}.conf ~/.config/hypr/themes/theme.conf 

# Dolphin (just reloading)
ACTIVE_WORKSPACE=$(hyprctl -j activeworkspace | jq '.id')
if [ "$(hyprctl -j clients | jq --arg wid "$ACTIVE_WORKSPACE" '.[] | select(.workspace.id == ($wid | tonumber)) | select(.class == "org.kde.dolphin") | .mapped')" == "true" ] ; then
    pkill -x dolphin
    dolphin &
fi

# Code (OSS) / vscode
VSCODE_THEME=$(awk -F '=' '/vscode/ {print $2}' "${HOME}/.config/swww/rices/${CURRENT_RICE}" | xargs)
sed -i "s|\"workbench.colorTheme\".*|\"workbench.colorTheme\": \"${VSCODE_THEME}\",|" ~/.config/Code/User/settings.json
sed -i "s|\"workbench.colorTheme\".*|\"workbench.colorTheme\": \"${VSCODE_THEME}\",|" ~/.config/Code\ -\ OSS/User/settings.json

# Swww
TRANSITION_TYPE=$(awk '/rice-transition/ {print $NF}' "$HOME/.config/material/config")

# you need dynamic `rose-pine-sddm` for this to work, check the installer for this option
cp -vrf ~/.config/swww/walls/${CURRENT_RICE}/${CURRENT_BG} /usr/share/sddm/themes/rose-pine-sddm/Backgrounds/current
swww img "$HOME/.config/swww/walls/${CURRENT_RICE}/$CURRENT_BG" \
    --transition-bezier .6,.94,.86,.23     \
    --transition-type grow                 \
    --transition-duration 0.65             \
    --transition-fps 144                   \
    --invert-y                             \
    --transition-pos "$(hyprctl cursorpos)"

hyprctl reload
