#!/bin/sh

CURRENT_RICE=$(awk '/rice-current/ {print $NF}' $HOME/.config/material/config)
CURRENT_WALL=$(awk '/wallpaper-current/ {print $NF}' $HOME/.config/material/config)

swww query
if [ $? -eq 1 ]; then
    swww-daemon --format xrgb

   [ $? -ne 0 ] && swww init
fi

wait
swww restore
