#!/usr/bin/env bash
set -euox pipefail

# Credits to: https://github.com/debxp/dmenu-scripts/blob/master/dmenu-kill-process
# Replace your launcher in the $launcher variable eg. rofi -dmenu or dmenu

# search root
root_path=$HOME

# Source scaling variables
source ~/.config/hypr/scripts/globalvars

prompt="-p Folder: "

file_path="$(find $root_path -maxdepth 5 -type d \( ! -regex '.*/\..*' \) | \
             sed 's|^'$root_path/'||' | sort | \
             rofi -config ~/.config/rofi/config_no-icons.rasi -dmenu -theme-str "${FONT_OVERRIDE_ROFI}" -theme-str "${BORDER_OVERRIDE_ROFI}" -i $prompt )"

if [[ ! -z $file_path ]]; then

    if [[ "$file_path" == "$root_path" ]]; then
        search_path=$root_path
    else
        search_path="$root_path/$file_path"
    fi

    total="$(find "$search_path" -maxdepth 1 -type f | wc -l)"
    
    if [[ $total -eq 0 ]]; then
        prompt="No files here!"
    else
        prompt="File:"
    fi

    file_name="$(find "$search_path" -maxdepth 1 -type f | \
                 awk -F'/' '{print $NF}' | \
                 rofi -config ~/.config/rofi/config_no-icons.rasi -dmenu -theme-str "${FONT_OVERRIDE_ROFI}" -i -p "$prompt" )"

    if [[ ! -z $file_name ]]; then
        xdg-open "$search_path/$file_name"
    fi

fi

exit 0
