#!/usr/bin/env bash
set -euox pipefail

# Credits to: https://github.com/debxp/dmenu-scripts/blob/master/dmenu-kill-process
# Replace your launcher in the $launcher variable eg. rofi -dmenu or dmenu

# Source scaling variables
source ~/.config/hypr/scripts/globalvars

prompt="-p Manual: "

# terminal to open manual
terminal="kitty"

# list all manuals
manual="$(man -k . | 
rofi -config ~/.config/rofi/config_no-icons.rasi -dmenu -theme-str "${FONT_OVERRIDE_ROFI}" -theme-str "${BORDER_OVERRIDE_ROFI}" $prompt | awk '{print $1}')"

# open selected manual with terminal
if [[ ! -z "$manual" ]]; then
    eval "$($terminal sh -c "man $manual")"
fi

exit 0
