#!/bin/sh

#LAUNCHER="wofi"
LAUNCHER="fuzzel"

THEME=$(dir -1 $HOME/.config/material/themes | $LAUNCHER --dmenu -i -p "~ Delete your preferred theme ~")
CHOICE=$(dir -1 $HOME/.config/wofi/manager/submenus/thememanager/confirm | $LAUNCHER --dmenu -i -p "Theme '$THEME' will be deleted permantly, are you sure?")

[[ "$CHOICE" == "Yes" ]] && rm -f $HOME/.config/material/themes/$THEME
