#!/bin/sh

#LAUNCHER="wofi"
LAUNCHER="fuzzel"

THEME=$(dir -1 $HOME/.config/material/themes | $LAUNCHER --dmenu -i -p "~ Load your preferred theme ~")
~/.config/hypr/scripts/load-config-material ~/.config/material/themes/$THEME 
