#!/bin/bash

# List of task managers in preferred order
PROGRAMS=("top" "htop" "btop")

# Variable to store the last found task PROGRAM
LAST_FOUND=""

# Function to check if a command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Loop through task managers list
for PROGRAM in "${PROGRAMS[@]}"; do
    if command_exists "$PROGRAM"; then
        echo "$PROGRAM is installed. Using $PROGRAM."
        LAST_FOUND="$PROGRAM" # Store the last found task PROGRAM
    else
        echo "$PROGRAM is not installed."
    fi
done

# If no task PROGRAM was found, exit with an error
if [ -z "$LAST_FOUND" ]; then
    echo "None of the task managers are installed. Exiting."
    exit 1
fi

# Run the last found task PROGRAM
echo "Launching $LAST_FOUND."
kitty "$LAST_FOUND"

