#!/bin/bash

### Wrapper for launching most available audiomixer
ERROR_MSG="Couldn't find a suitable audiomixer... please install one of the following programs: \n      - pavucontrol\n     - pavucontrol-qt\n      - alsamixer\n"

# List of mixers in preferred order
PROGRAMS=(
    "alsamixer"
    "pavucontrol"
    "pavucontrol-qt"
)

# Variable to store the last found task PROGRAM
LAST_FOUND=""

# Function to check if a command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Loop through task managers list
for PROGRAM in "${PROGRAMS[@]}"; do
    if command_exists "$PROGRAM"; then
        echo "$PROGRAM is installed. Using $PROGRAM."
        LAST_FOUND="$PROGRAM" # Store the last found task PROGRAM
    else
        echo "$PROGRAM is not installed."
    fi
done

# If no task PROGRAM was found, exit with an error and log it
if [ -z "$LAST_FOUND" ]; then
    echo "$ERROR_MSG" >> /tmp/material/$(id -u)audiomixer-launch.log
    exit 1
fi

# Run the last found task PROGRAM
if [[ "$LAST_FOUND" == "alsamixer" ]]; then
    kitty $LAST_FOUND &
    exit 0
fi

$LAST_FOUND
