#!/bin/sh

RED='\033[01;31m'
PUR='\033[01;35m'
CLR='\033[00m'
CONF_DIR="/home/${USER}/.config"
THEME_RICE="$(cat "${CONF_DIR}/swww/current/rice")"
WAYBAR_RICE="$(cat "${CONF_DIR}/waybar/current/rice")"
CURSOR="$(grep "Gtk/CursorThemeName" "${CONF_DIR}/xsettingsd/xsettingsd.conf" | awk '{print $2}' | tr -d =\"= )"
WALLPAPER="$(cat "${CONF_DIR}/swww/current/name")"
GTK_THEME="$(grep -m 1 "=" "${CONF_DIR}/gtk-3.0/settings.ini" | tail -n 1 | awk -F '=' '{print $2}')"
GTK_ICONS="$(grep -m 2 "=" "${CONF_DIR}/gtk-3.0/settings.ini" | tail -n 1 | awk -F '=' '{print $2}')"
QT_THEME="$(grep -m 3 "=" "${CONF_DIR}/qt5ct/qt5ct.conf" | tail -n 1 | awk -F '=' '{print $2}')"

echo "System Theme: ${THEME_RICE}"
echo "Waybar Theme: ${WAYBAR_RICE}"
echo "Cursor: ${CURSOR}"
echo "Wallpaper: ${WALLPAPER}"
echo "GTK Theme: ${GTK_THEME}"
echo "GTK Icons: ${GTK_ICONS}"
echo "Qt5 Theme: ${QT_THEME}"
