#!/bin/sh

CONF_DIR="/home/${USER}/.config"
THEME_RICE="$(cat "${CONF_DIR}/swww/current/rice")"
WAYBAR_RICE="$(cat "${CONF_DIR}/waybar/current/rice")"
TRANSITION_TYPE="$(cat "${CONF_DIR}/swww/current/transition")"
CURSOR="$(grep "Gtk/CursorThemeName" "${CONF_DIR}/xsettingsd/xsettingsd.conf" | awk '{print $2}' | tr -d =\"= )"
WALLPAPER="$(cat "${CONF_DIR}/swww/current/name")"
WLOGOUT_THEME="$(grep -m 1 "=" "${CONF_DIR}/hypr/scripts/manage-wlogout" | tail -n 1 | awk -F '=' '{print $2}' | tr -d =\"=)"
GTK_THEME="$(grep -m 1 "=" "${CONF_DIR}/gtk-3.0/settings.ini" | tail -n 1 | awk -F '=' '{print $2}')"
GTK_FONT="$(grep -m 3 "=" "${CONF_DIR}/gtk-3.0/settings.ini" | tail -n 1 | awk -F '=' '{print $2}')"
GTK_ICONS="$(grep -m 2 "=" "${CONF_DIR}/gtk-3.0/settings.ini" | tail -n 1 | awk -F '=' '{print $2}')"
QT_THEME="$(grep -m 3 "=" "${CONF_DIR}/qt5ct/qt5ct.conf" | tail -n 1 | awk -F '=' '{print $2}')"

BLACK_='\033[01;30m'   # Black
RED___='\033[01;31m'   # Red
GREEN_='\033[01;32m'   # Green
YELLOW='\033[01;33m'   # Yellow
BLUE__='\033[01;34m'   # Blue
PURPLE='\033[01;35m'   # Purple
CYAN__='\033[01;36m'   # Cyan
WHITE_='\033[01;37m'   # White
BOLD__='\033[1m'       # Bold
RESET_='\033[00m'      # Reset

echo -e "${RESET_}
${PURPLE}       .              
${PURPLE}      / \                           __                     __
${PURPLE}     /   \         _______  _______/ /____  ____ ___  ____/ /
${PURPLE}    /^.   \      /  ___/ / / / ___/ __/ _ \/ __ \`__ \/ __  / 
${PURPLE}   /  .-.  \     (__  ) /_/ (__  ) /_/  __/ / / / / / /_/ /  
${CYAN__}  /  (   ) _\   /____/\__, /____/\__/\___/_/ /_/ /_/\__,_/   
${CYAN__} / _.~   ~._^\       /____/                                  
${CYAN__}/.^         ^.\ 
${WHITE_} 
${WHITE_} "

echo -e "${RED___}▉▉  |${RESET_} System Theme${BLACK_} ....... ${RESET_}${BOLD__}${THEME_RICE}"
echo -e "${RED___}  ▉▉|${RESET_} Waybar Theme${BLACK_} ....... ${RESET_}${BOLD__}${WAYBAR_RICE}"
echo -e "${WHITE_}▉▉  |${RESET_} Cursor${BLACK_} ............. ${RESET_}${BOLD__}${CURSOR}"
echo -e "${WHITE_}  ▉▉|${RESET_} Wallpaper${BLACK_} .......... ${RESET_}${BOLD__}${WALLPAPER}"
echo -e "${BLUE__}▉▉  |${RESET_} GTK Theme${BLACK_} .......... ${RESET_}${BOLD__}${GTK_THEME}"
echo -e "${BLUE__}  ▉▉|${RESET_} GTK Icons${BLACK_} .......... ${RESET_}${BOLD__}${GTK_ICONS}"
echo -e "${YELLOW}▉▉  |${RESET_} Qt5 Theme${BLACK_} .......... ${RESET_}${BOLD__}${QT_THEME}"
echo -e "${YELLOW}  ▉▉|${RESET_} GTK Font${BLACK_} ........... ${RESET_}${BOLD__}${GTK_FONT}"
echo -e "${PURPLE}▉▉  |${RESET_} Swww Transition${BLACK_} .... ${RESET_}${BOLD__}${TRANSITION_TYPE}"
echo -e "${PURPLE}  ▉▉|${RESET_} Wlogout Theme${BLACK_} ...... ${RESET_}${BOLD__}${WLOGOUT_THEME}"
echo 
