#!/bin/sh

set -euox pipefail

HYPR_PATH="$HOME/.config/hypr"
DEFAULT_DIR="$HOME/.config/material"
DEFAULT_CONFIG="config"
SEL_CONFIG="${1:-$DEFAULT_DIR/$DEFAULT_CONFIG}"

### BACKUP AND OVERWRITE CONFIG ###
cp -dvfr ~/.config/material/config ~/.config/material/backups/config_${RANDOM}.bak
[[ $SEL_CONFIG == ~/.config/material/config ]] || cp -dvfr $SEL_CONFIG ~/.config/material/config

### RESTORE MATERIAL SETTINGS ###
## hyprland.conf
CORNER_ROUNDING=$(awk '/corner-rounding/ {print $NF}' $SEL_CONFIG)
TILING_LAYOUT=$(awk '/tiling-layout/ {print $NF}' $SEL_CONFIG)
GAPS_IN=$(awk '/gaps-in/ {print $NF}' $SEL_CONFIG)
GAPS_OUT=$(awk '/gaps-out/ {print $NF}' $SEL_CONFIG)
BORDER_SIZE=$(awk '/border-size/ {print $NF}' $SEL_CONFIG)

sed -i 's|rounding =.*|rounding = '$CORNER_ROUNDING'|' "$HYPR_PATH/decoration.conf"
sed -i 's|layout =.*|layout = '$TILING_LAYOUT'|' "$HYPR_PATH/hyprland.conf"
sed -i 's|gaps_in =.*|gaps_in = '$GAPS_IN'|' "$HYPR_PATH/hyprland.conf"
sed -i 's|gaps_out =.*|gaps_out = '$GAPS_OUT'|' "$HYPR_PATH/hyprland.conf"
sed -i 's|border_size =.*|border_size = '$BORDER_SIZE'|' "$HYPR_PATH/hyprland.conf"

## decoration.conf
BLUR_SIZE=$(awk '/blur-size/ {print $NF}' $SEL_CONFIG)
BLUR_PASSES=$(awk '/blur-passes/ {print $NF}' $SEL_CONFIG)
BLUR_STATE=$(awk '/blur-state/ {print $NF}' $SEL_CONFIG)

sed -i 's|size =.*|size = '$BLUR_SIZE'|' "$HYPR_PATH/decoration.conf"
sed -i 's|passes =.*|passes = '$BLUR_PASSES'|' "$HYPR_PATH/decoration.conf"
[[ "$BLUR_STATE" == "on" ]] && sed -i 's|layerrule = blur,waybar.*|layerrule = blur,waybar|' "$HYPR_PATH/decoration.conf" || sed -i 's|layerrule = blur,waybar.*|#layerrule = blur,waybar|' "$HYPR_PATH/decoration.conf" 

## animations.conf
ANIMATIONS_STATE=$(awk '/animations-state/ {print $NF}' $SEL_CONFIG)
ANIMATIONS_CURRENT=$(awk '/animations-current/ {print $NF}' $SEL_CONFIG)

sed -i 's|source =.*|source = ~/.config/hypr/animations/'$ANIMATIONS_CURRENT'.conf |' "$HYPR_PATH/animations.conf"
sed -i 's|enabled =.*|enabled = '$ANIMATIONS_STATE'|' "$HYPR_PATH/animations.conf"

### LOAD ALL NECESSARY CHANGES ###
RICE_CURRENT=$(awk '/rice-current/ {print $NF}' $SEL_CONFIG)
WAYBAR_CURRENT=$(awk '/bar-current/ {print $NF}' $SEL_CONFIG)
WALLPAPER_CURRENT=$(awk '/wallpaper-current/ {print $NF}' $SEL_CONFIG)

~/.config/swww/scripts/change_theme $RICE_CURRENT $WALLPAPER_CURRENT
hyprctl reload
