#!/bin/sh

BAR_CURRENT="$(awk '/bar-current/ {print $NF}' $HOME/.config/material/config)"
BAR_STATE="$(awk '/bar-state/ {print $NF}' $HOME/.config/material/config)"
CURRENT_WAYBAR_CALL="waybar -c $HOME/.config/waybar/bar/${BAR_CURRENT}/config.jsonc -s $HOME/.config/waybar/bar/${BAR_CURRENT}/style.css"

# Check if waybar is turned off and exit
[[ "$BAR_STATE" == "off" ]] && exit 128

if pgrep -x "waybar" >/dev/null; then
    pkill -x "waybar"
    $CURRENT_WAYBAR_CALL
else 
    $CURRENT_WAYBAR_CALL
fi
