#!/usr/bin/env sh

#LAUNCHER="wofi"
LAUNCHER="fuzzel"

# Check if wofi is already running
if pgrep -x "$LAUNCHER" >/dev/null; then
    pkill -x "$LAUNCHER"
    exit 0
fi

case "$1" in
    "wofi")
        $LAUNCHER
        ;;
    "wallpaper")
        ~/.config/wofi/scripts/wofi-wallpaper
        ;;
    "emoji")
        ~/.config/wofi/scripts/wofi-emoji
        ;;
    "rice")
        ~/.config/wofi/scripts/wofi-rice-selector -
        ;;

    ### WARNING: Will be deprecated, breaks a LOT of shit
    "theme")
        ~/.config/wofi/scripts/wofi-rice-selector theme         
        ;;
    ###
    
    "manager")
        ~/.config/wofi/scripts/wofi-manager "main"
        ;;
    "waybar")
        ~/.config/wofi/scripts/wofi-waybar-selector
        ;;
    "cliphist")
        cliphist list | $LAUNCHER --dmenu -p "~ Material clipboard selection ~" -i | cliphist decode | wl-copy
        ;;
    *)
        echo "Invalid choice $1"
        pkill -x "$LAUNCHER"
        ;;
esac
