#!/bin/sh

PID=$(pgrep -f "kitty --class quake")
WSP=$(hyprctl activeworkspace | grep ID | awk '{print $3}' | grep -oE '^[[:space:]]*[0-9]+')
SPC=$(hyprctl workspaces | grep special)

if [ -n "$SPC" ]; then
    hyprctl dispatch movetoworkspace "$WSP,pid:$PID"
else
    hyprctl dispatch movetoworkspacesilent special,pid:$PID
fi
