#!/bin/sh

set -euox pipefail

BAR_NAME=${1:-"Polybar-Top"}
FLAG=${2:-""} # magic

function set_hypr_blurls() {
    sed -i 's|.*layerrule = blur,waybar.*|    layerrule = blur,waybar|' ~/.config/hypr/decoration.conf
    sed -i 's|^blur-state.*|blur-state = on|' ~/.config/material/config
}

function unset_hypr_blurls() {
    sed -i 's|.*layerrule = blur,waybar.*|    #layerrule = blur,waybar|' ~/.config/hypr/decoration.conf
    sed -i 's|^blur-state.*|blur-state = off|' ~/.config/material/config
}

function save_config() {
    sed -i 's|^bar-current.*|bar-current = '${BAR_NAME}'|' ~/.config/material/config
}

save_config

# Check if bar specifies blur
BLUR_FLAG="$(grep "blurls" "$HOME/.config/waybar/rices/$BAR_NAME" | awk -F '=' '{print $2}' | xargs)"
[[ "$BLUR_FLAG" == "true" ]] && set_hypr_blurls || unset_hypr_blurls

~/.config/hypr/scripts/manage-waybar >/dev/null 2>&1 &
