#!/bin/sh

PERLTONE_STATUS=$(awk '/perltone-status/ {print $NF}' $HOME/.config/material/config | xargs)
if [[ "$PERLTONE_STATUS" == "on" ]] ; then
    dunstify "Material" "Perltone is disabled" --timeout=2500
    sed -i 's|perltone-status.*|perltone-status = off|' $HOME/.config/material/config
else
    dunstify "Material" "Perltone is enabled" --timeout=2500
    sed -i 's|perltone-status.*|perltone-status = on|' $HOME/.config/material/config
fi

~/.config/hypr/scripts/load-config-material
