#!/bin/sh

HYPRGAMEMODE=$(hyprctl getoption animations:enabled | awk 'NR==1{print $2}' | xargs)
if [[ "$HYPRGAMEMODE" == 1 ]] ; then
    hyprctl --batch "\
        keyword animations:enabled 0;\
        keyword decoration:drop_shadow 0;\
        keyword decoration:blur:enabled 0;\
        keyword general:gaps_in 0;\
        keyword general:gaps_out 0;\
        keyword general:border_size 1;\
        keyword decoration:rounding 0"
    dunstify "Material" "Gamemode is enabled" --timeout=2500
    exit
else
    dunstify "Material" "Gamemode is disabled" --timeout=2500
fi


hyprctl reload
