#!/usr/bin/env sh

WAYBAR_CALL="$(waybar -c ~/.config/waybar/bar/bottom/config.jsonc -s ~/.config/waybar/bar/bottom/style.css)"
# Check if wlogout is already running
if pgrep -x "waybar" >/dev/null; then
    pkill -x "waybar"
    WAYBAR_CALL
    exit 0
else 
    WAYBAR_CALL
fi
