#!/usr/bin/env sh

# Check if wofi is already running
if pgrep -x "wofi" >/dev/null; then
    pkill -x "wofi"
    exit 0
fi

case "$1" in
    "wofi")
        wofi
        ;;
    "wallpaper")
        wofi-wallpaper
        ;;
    "emoji")
        wofi-emoji
        ;;
    "rice")
        wofi-rice-selector
        ;;
    "manager")
        wofi-manager "main"
        ;;
    "cliphist")
        cliphist list | wofi --dmenu | cliphist decode | wl-copy
        ;;
    "waybar")
        wofi-waybar-selector
        ;;
    *)
        echo "Invalid choice $1"
        pkill -x "wofi"
        ;;
esac
