#!/usr/bin/env sh

# Check if wlogout is already running
if pgrep -x "waybar" >/dev/null; then
    pkill -x "waybar"
    waybar -c ~/.config/waybar/bar/bottom/config.jsonc -s ~/.config/waybar/bar/bottom/style.css
    exit 0
else 
    waybar -c ~/.config/waybar/bar/bottom/config.jsonc -s ~/.config/waybar/bar/bottom/style.css
fi
