#!/usr/bin/env sh

# Check if wlogout is already running
if pgrep -x "wofi" >/dev/null; then
    pkill -x "wofi"
    exit 0
fi

#wofi-emoji --height 590px \
#           --width 1140px \
#           --allow-images true
wofi-emoji
