#!/bin/sh

LAUNCHER=$(awk -F '=' '/material-launcher/ {print $2}' $HOME/.config/material/config)
[[ $(echo $LAUNCHER | xargs) == "rofi" ]] && LAUNCHER="rofi -config ~/.config/rofi/config_no-icons.rasi -dmenu " || LAUNCHER="$LAUNCHER --dmenu" # patch for rofi

[ ! -e $HOME/.config/hypr/resolutions ] && $HOME/.config/hypr/scripts/generate-resolutions
RESOLUTION=$(dir -1 $HOME/.config/hypr/resolutions | $LAUNCHER -i -p "~ Load your preferred resolution ~")

[[ $RESOLUTION == "" ]] && exit 1

rm -v $HOME/.config/hypr/monitors.conf
touch $HOME/.config/hypr/monitors.conf

cat $HOME/.config/hypr/resolutions/$RESOLUTION > $HOME/.config/hypr/monitors.conf

hyprctl reload
wait
$HOME/.config/hypr/scripts/load-config-material
