[colors.bright]
black = "0x777777"
blue = "0x9e9e9e"
cyan = "0xededed"
green = "0x989898"
magenta = "0xfafafa"
red = "0xffffff"
white = "0xffffff"
yellow = "0xe0e0e0"

[colors.normal]
black = "0x4e4e4e"
blue = "0xafafaf"
cyan = "0x929292"
green = "0x848484"
magenta = "0x9c9c9c"
red = "0xb8b8b8"
white = "0x6e6e6e"
yellow = "0x7f7f7f"

[colors.primary]
background = "0x282828"
foreground = "0x939393"
