colors:
  # Default colors
  primary:
    background: '0x282828'
    foreground: '0x939393'

  # Normal colors
  normal:
    black:   '0x4e4e4e'
    red:     '0xb8b8b8'
    green:   '0x848484'
    yellow:  '0x7f7f7f'
    blue:    '0xafafaf'
    magenta: '0x9c9c9c'
    cyan:    '0x929292'
    white:   '0x6e6e6e'

  # Bright colors
  bright:
    black:   '0x777777'
    red:     '0xffffff'
    green:   '0x989898'
    yellow:  '0xe0e0e0'
    blue:    '0x9e9e9e'
    magenta: '0xfafafa'
    cyan:    '0xededed'
    white:   '0xffffff'

