#!/bin/sh

DIR="${HOME}/.config/swww/walls"
CURRENT_BG="$(find "$DIR" -name '*.jpg' -o -name '*.png' | shuf -n1)"

# Check if the program is running
if pgrep "swww-deamon" >/dev/null; then
	swww init
fi

#i dont know kekw: .16,.33,1,.46
#hyprdots:         .43,1.19,1,.4  https://github.com/prasanthrangan/hyprdots/blob/main/Configs/.config/hypr/scripts/swwwallpaper.sh
#ease-in-out:      .6,.94,.86,.23
#ease`ish:         .75,.47,.29,.83
swww img "$CURRENT_BG" \
    --transition-bezier .6,.94,.86,.23\
    --transition-type "grow" \
    --transition-duration 1 \
    --transition-fps 144 \
    --invert-y \
    --transition-pos "$( hyprctl cursorpos )"

#swww img "$BG" \
#    --transition-type wipe \
#    --transition-pos "$(hyprctl cursorpos)" \
#    --invert-y \
#    --transition-fps 60 \
#    --transition-angle 30 \
#    --transition-step 90

### transitions:
#"none"
#"simple"
#"left"
#"right"
#"top"
#"bottom"
#"wipe"
#"grow"
#"center"
#"outer"
#"any"
#"wave"
#"random"
#"fade"
