#!/bin/sh

source ./functions
if [ $? -ne 0 ]; then
    echo "Error: can't source functions, execute the script from $(dirname "$(realpath "$0")")"
    exit 1
fi

ARCHIVE_DIR="../archives"
extract_archive() {
    local TYPE=$1
    local DESTINATION=$2
    [ -e "$DESTINATION" ] || mkdir -p $DESTINATION

    for THEME in $(ls -1 ${ARCHIVE_DIR}/${TYPE}_*); do
        sudo tar -xf ${ARCHIVE_DIR}/${THEME} -C $DESTINATION
    done
}

# Extract archives using the functions above
extract_archive "Font" "$HOME/.local/share/fonts" # Fonts
extract_archive "Gtk" "$HOME/.local/share/themes" # Gtk themes
extract_archive "Icon" "$HOME/.local/share/icons" # Icon themes
