#!/bin/sh

# import functions
source ./functions
if [ $? -ne 0 ]; then
    echo "Error: can't source functions, execute the script from $(dirname "$(realpath "$0")")"
    exit 1
fi

# Get Packages using imported functions from `packages.yaml`
BASE_PACKAGES=$(get_yaml_packages packages.yaml base_packages)
MINIMAL_PACKAGES=$(get_yaml_packages packages.yaml minimal_packages)
EXTENDED_PACKAGES=$(get_yaml_packages packages.yaml extended_packages)
GAMING_PACKAGES=$(get_yaml_packages packages.yaml gaming_packages)
SDDM_PACKAGES=$(get_yaml_packages packages.yaml sddm_packages)
OPTIONAL_PACKAGES_RUST=$(get_yaml_packages packages.yaml optional_packages_rust)
TTY_PACKAGES=$(get_yaml_packages packages.yaml tty_packages)

# Detect nvidia and install drivers
if detect_nvidia; then
    echo -e "[${PURPLE}info${RESET}] Found an nvidia card installing dkms to package list..."
    ./install_nvidia
    install_packages nvidia-dkms pacman
else
    echo -e "[${PURPLE}info${RESET}] No nvidia card detected skipping dkms..."
fi

# check for wifi and configure pacman + get options
check_wifi
if [ $? -ne 0 ]; then
    echo -e "[${RED}fail${RESET}] Internet connection required, please connect to a network!"
    exit 1
else
    echo -e "[${BLUE}ok${RESET}] Found internet connection" 
    configure_pacman
    fix_groups
    install_yay

    source ./install_get_options
fi

### These are functions used in the script, 
# See the bottom of the file for the call into `stage_1`
enable_sddm_quest() {
    if [[ $SDDM_INSTALL == "y" || $SDDM_INSTALL == "Y" || $SDDM_INSTALL == "" || $SDDM_CUSTOM_INSTALL == "y" || $SDDM_CUSTOM_INSTALL == "Y" || $SDDM_CUSTOM_INSTALL == "" ]]; then

        echo -e "\n${WHITE_BOLD}Do you want to enable sddm now? (y/n)${RESET}"
        read -n1 -rep "$: " SDDM_ENABLE

        if [[ $SDDM_ENABLE == "y" || $SDDM_ENABLE == "Y" || $SDDM_ENABLE == "" ]]; then
            echo -e "[${BLUE}ok${RESET}] Enabled sddm successfully"
            sudo systemctl enable sddm.service
            sudo systemctl start sddm.service
        else
            echo -e "[${PURPLE}info${RESET}] Skipping enabling of sddm.service"
            echo -e "[${PURPLE}info${RESET}] You can enable sddm manually with:"
            echo -e "[${PURPLE}info${RESET}] 'sudo systemctl enable sddm.service'"
        fi
    else 
        echo -e "[${PURPLE}info${RESET}] Skipping enabling of sddm.service"
    fi 
}

install_sddm() {
    if [[ $SDDM_INSTALL == "y" || $SDDM_INSTALL == "Y" || $SDDM_INSTALL == "" ]]; then
        echo -e "[${PURPLE}info${RESET}] Installing sddm packages"
        for PACKAGE in ${SDDM_PACKAGES[@]}; do
            install_packages $PACKAGE yay
        done

        if [[ $SDDM_CUSTOM_INSTALL == "y" || $SDDM_CUSTOM_INSTALL == "Y" || $SDDM_CUSTOM_INSTALL == "" ]]; then
            install_custom_sddm
        else 
            echo -e "[${PURPLE}info${RESET}] Skipping custom sddm theme"
        fi
    else
        echo -e "[${PURPLE}info${RESET}] Skipping sddm packages"
    fi
}

stage_1() {
    echo -e "[${PURPLE}info${RESET}] Executing Stage 1"

    echo -e "[${PURPLE}info${RESET}] Installing base packages"
    for PACKAGE in ${BASE_PACKAGES[@]}; do
        install_packages $PACKAGE yay
    done

    echo -e "[${PURPLE}info${RESET}] Copying config files..."
    copy_config 
    set_hypr_modkey $MODKEY # change to user preferred modkey

    echo -e "[${PURPLE}info${RESET}] Starting Services..."
    start_services
    install_sddm

    if [[ $INSTALL_TTY == "y" || $INSTALL_TTY == "Y" || $INSTALL_TTY == "" || $INSTALL_TTY == "y" || $INSTALL_TTY == "Y" || $INSTALL_TTY == "" ]]; then
        for PACKAGE in ${TTY_PACKAGES[@]}; do
            install_packages $PACKAGE yay
        done
        
        set_tty_font
    fi

    if [[ $OPTIONAL_DEPS_RUST == "y" || $OPTIONAL_DEPS_RUST == "Y" || $OPTIONAL_DEPS_RUST == "" || $OPTIONAL_DEPS_RUST == "y" || $OPTIONAL_DEPS_RUST == "Y" || $OPTIONAL_DEPS_RUST == "" ]]; then
        for PACKAGE in ${OPTIONAL_PACKAGES_RUST[@]}; do
            install_packages $PACKAGE yay
        done
    fi

    echo -e "[${PURPLE}info${RESET}] Trying to switch stage..."
    if [ $STAGE -gt 1 ]; then 
        echo -e "[${PURPLE}info${RESET}] Entering stage 2"
        stage_2
    else 
        echo -e "[${BLUE}ok${RESET}] Stage-${STAGE} installation finished!"
        enable_sddm_quest
    fi
}

stage_2() {
    echo -e "Executing Stage 2"

    echo -e "[${PURPLE}info${RESET}] Installing minimal packages"
    for PACKAGE in ${MINIMAL_PACKAGES[@]}; do
        install_packages $PACKAGE yay
    done
   
    echo -e "[${PURPLE}info${RESET}] Trying to switch stage..."
    if [ $STAGE -gt 2 ]; then 
        echo -e "[${PURPLE}info${RESET}] Entering stage 3"
        stage_3
    else 
        echo -e "[${BLUE}ok${RESET}] Stage-${STAGE} installation finished!"
        enable_sddm_quest
    fi
}

stage_3() {
    echo -e "[${PURPLE}info${RESET}] Executing Stage 3"

    echo -e "[${PURPLE}info${RESET}] Installing extended packages..."
    for PACKAGE in ${EXTENDED_PACKAGES[@]}; do
        install_packages $PACKAGE yay
    done

    echo -e "[${PURPLE}info${RESET}] Trying to switch stage..."
    if [ $STAGE -gt 3 ]; then 
        echo -e "[${PURPLE}info${RESET}] Entering stage 4"
        stage_4
    else 
        echo -e "[${BLUE}ok${RESET}] Stage-${STAGE} installation finished!"
        enable_sddm_quest
    fi
}

stage_4() {
    echo -e "[${PURPLE}info${RESET}] Executing Stage 4"

    echo -e "[${PURPLE}info${RESET}] Installing gaming packages"
    for PACKAGE in ${GAMING_PACKAGES[@]}; do
        install_packages $PACKAGE yay
    done

    echo -e "Stage-${STAGE} installation finished!"
    enable_sddm_quest
}

stage_1

# Extract gtk themes and fonts into correct directories
./install_archives

# Fix wrong symlinks because they depend on the username
./install_fix_symlinks

# Ask to reboot
echo -e "[${BLUE}ok${RESET}] Installation finished, please reboot to apply all changes" 
echo -e "\n${WHITE_BOLD}Do you want to reboot now? (y/n)${RESET}"
read -n1 -rep "$: " REBOOT_FLAG

if [[ $REBOOT_FLAG == "y" || $REBOOT_FLAG == "Y" || $REBOOT_FLAG == "" ]]; then
    systemctl reboot
fi
