#!/bin/sh

# import functions
source ./functions
if [ $? -ne 0 ]; then
    echo "Error: can't source functions, execute the script from $(dirname "$(realpath "$0")")"
    exit 1
fi

echo -e "[${PURPLE}info${RESET}] Copying configs..."

# Enable dotglob to include files starting with a dot
shopt -s dotglob

# cleanup old confs before installing
rm -r "$HOME/.config/Code/">/dev/null 2>&1 
rm -r "$HOME/.config/Code - OSS/">/dev/null 2>&1 
rm -r "$HOME/.config/Kvantum/">/dev/null 2>&1 
rm -r "$HOME/.config/VSCodium/">/dev/null 2>&1 
rm -r "$HOME/.config/btop/">/dev/null 2>&1 
rm -r "$HOME/.config/cava/">/dev/null 2>&1 
rm -r "$HOME/.config/dunst/">/dev/null 2>&1 
rm -r "$HOME/.config/fastfetch/">/dev/null 2>&1 
rm -r "$HOME/.config/gtk-3.0/">/dev/null 2>&1 
rm -r "$HOME/.config/hypr/">/dev/null 2>&1 
rm -r "$HOME/.config/kitty/">/dev/null 2>&1 
rm -r "$HOME/.config/material/config">/dev/null 2>&1 
rm -r "$HOME/.config/nwg-look/">/dev/null 2>&1 
rm -r "$HOME/.config/qt5ct/">/dev/null 2>&1 
rm -r "$HOME/.config/qt6ct/">/dev/null 2>&1 
rm -r "$HOME/.config/rofi/">/dev/null 2>&1 
rm -r "$HOME/.config/swww/">/dev/null 2>&1 
rm -r "$HOME/.config/udiskie/">/dev/null 2>&1 
rm -r "$HOME/.config/waybar/">/dev/null 2>&1 
rm -r "$HOME/.config/wlogout/">/dev/null 2>&1 
rm -r "$HOME/.config/xsettingsd/">/dev/null 2>&1 
rm -r "$HOME/.config/arkrc">/dev/null 2>&1 
rm -r "$HOME/.config/code-flags.conf">/dev/null 2>&1 
rm -r "$HOME/.config/codium-flags.conf">/dev/null 2>&1 
rm -r "$HOME/.config/dolphinrc">/dev/null 2>&1 
rm -r "$HOME/.config/electron-flags.conf">/dev/null 2>&1 
rm -r "$HOME/.config/kdeglobals">/dev/null 2>&1 
rm -r "$HOME/.config/spotify-flags.conf">/dev/null 2>&1 

# Function to copy files recursively
copy_files() {
    local SOURCE="$1"
    local DESTINATION="$2"
    local RELATIVE_PATH="$3"

    rsync -a --links --info=progress2 "$SOURCE/" "$DESTINATION/$RELATIVE_PATH/"
    echo -e "[${BLUE}ok${RESET}] Synced $SOURCE → $DESTINATION/$RELATIVE_PATH"

    # stop hyprland screaming
    hyprctl reload >/dev/null 2>&1
}

# Source directory
SOURCE_HOME="$(realpath ../configs/home)"

# Destination directory
DESTINATION_HOME="$(realpath $HOME)"

# Call the function to copy files recursively
copy_files "$SOURCE_HOME" "$DESTINATION_HOME"

# Disable dotglob to restore default behavior
shopt -u dotglob

sudo rm -f /etc/issue ; sudo cp -r ../configs/root/etc/issue /etc && echo -e "[${BLUE}ok${RESET}] Copied issue to /etc/issue"
sudo rm -f /etc/motd ; sudo cp -r ../configs/root/etc/motd /etc && echo -e "[${BLUE}ok${RESET}] Copied motd to /etc/motd"
sudo rm -f /etc/sddm.conf ; sudo cp -r ../configs/root/etc/sddm.conf /etc && echo -e "[${BLUE}ok${RESET}] Copied sddm.conf to /etc/sddm.conf"

echo -e "[${PURPLE}info${RESET}] Cleaning out conflicting xdg portals..."
sudo pacman -R $FLAGS xdg-desktop-portal-gnome xdg-desktop-portal-gtk >/dev/null 2>&1 
