#!/bin/sh

# import functions
source ./functions
if [ $? -ne 0 ]; then
    echo "Error: can't source functions, execute the script from $(dirname "$(realpath "$0")")"
    exit 1
fi

if package_installed firefox; then
    echo -e "[${BLUE}ok${RESET}] Firefox already installed"
else
    echo -e "[${PURPLE}info${RESET}] Installing firefox"
    install_packages firefox pacman
fi

FIREFOX_DIR="${HOME}/.mozilla/firefox"
PROFILE_DIR=$(find "${FIREFOX_DIR}" -maxdepth 1 -type d -name "*.default*")

PROFILES=($(echo ${PROFILE_DIR}))
for PROFILE in "${PROFILES[@]}"; do
    SOURCE_DIR="${HOME}/.cache/material/Firefox_Preferences"

    if [ -e "$PROFILE" ]; then
        [ -e "${PROFILE}/chrome" ] || mkdir -p "${PROFILE}/chrome"
        cp "${SOURCE_DIR}/userChrome.css" "${PROFILE}/chrome/userChrome.css"
        cp "${SOURCE_DIR}/userContent.css" "${PROFILE}/chrome/userContent.css"
        cp "${SOURCE_DIR}/user.js" "${PROFILE}/user.js"
        echo -e "[${BLUE}ok${RESET}] Copied Firefox preferences to ${PROFILE}"
    else
        echo "Firefox profile directory not found."
    fi
done
