#!/bin/sh

# Script to fix really old versions of Material. Should not be needed anymore.

rm -r "${HOME}/.config/hypr/resolutions"
rm -r "${HOME}/.cache/material"

$HOME/.config/hypr/scripts/load-config-material >/dev/null 2>&1 & disown >/dev/null 2>&1
sleep 5
