#!/bin/sh

KEYMAPS=(
    "us" #              USA
    "ad" #              Andorra
    "af" #              Afghanistan
    "ara" #             Arabic
    "al" #              Albania
    "am" #              Armenia
    "az" #              Azerbaijan
    "by" #              Belarus
    "be" #              Belgium
    "bd" #              Bangladesh
    "in" #              India
    "ba" #              Bosnia and Herzegovina
    "br" #              Brazil
    "bg" #              Bulgaria
    "ma" #              Morocco
    "mm" #              Myanmar
    "ca" #              Canada
    "cd" #              Congo, Democratic Republic of the
    "cn" #              China
    "hr" #              Croatia
    "cz" #              Czechia
    "dk" #              Denmark
    "nl" #              Netherlands
    "bt" #              Bhutan
    "ee" #              Estonia
    "ir" #              Iran
    "iq" #              Iraq
    "fo" #              Faroe Islands
    "fi" #              Finland
    "fr" #              France
    "gh" #              Ghana
    "gn" #              Guinea
    "ge" #              Georgia
    "de" #              Germany
    "gr" #              Greece
    "hu" #              Hungary
    "is" #              Iceland
    "il" #              Israel
    "it" #              Italy
    "jp" #              Japan
    "kg" #              Kyrgyzstan
    "kh" #              Cambodia
    "kz" #              Kazakhstan
    "la" #              Laos
    "latam" #           Latin American
    "lt" #              Lithuania
    "lv" #              Latvia
    "mao" #             Maori
    "me" #              Montenegro
    "mk" #              Macedonia
    "mt" #              Malta
    "mn" #              Mongolia
    "no" #              Norway
    "pl" #              Poland
    "pt" #              Portugal
    "ro" #              Romania
    "ru" #              Russia
    "rs" #              Serbia
    "si" #              Slovenia
    "sk" #              Slovakia
    "es" #              Spain
    "se" #              Sweden
    "ch" #              Switzerland
    "sy" #              Syria
    "tj" #              Tajikistan
    "lk" #              Sri Lanka
    "th" #              Thailand
    "tr" #              Turkey
    "tw" #              Taiwan
    "ua" #              Ukraine
    "gb" #              United Kingdom
    "uz" #              Uzbekistan
    "vn" #              Vietnam
    "kr" #              Korea, Republic of
    "ie" #              Ireland
    "pk" #              Pakistan
    "mv" #              Maldives
    "za" #              South Africa
    "epo" #             Esperanto
    "np" #              Nepal
    "ng" #              Nigeria
    "et" #              Ethiopia
    "sn" #              Senegal
    "tm" #              Turkmenistan
    "ml" #              Mali
    "tz" #              Tanzania
)