#!/bin/sh

PACKAGES=(
  "rsync"

#  -- Audio Server + Recording --
  "pipewire"
  "pipewire-alsa"
  "pipewire-audio"
  "pipewire-jack"
  "pipewire-pulse"
  "gst-plugin-pipewire"
  "wireplumber"

#  -- Window manager stuff --
  "hyprland"
  "hyprpicker"
  "cliphist"
  "kitty"
  "waybar"
  "polkit-gnome"
  "swww"
  "wlogout"
  
#  -- Screenshots --
  "swappy"
  "grim"
  "slurp"

#  -- File management --
  "dolphin"
  "qt5-imageformats"
  "ffmpegthumbs"
  "kde-cli-tools"
  "archlinux-xdg-menu"

#  -- CLI Tools --
  "python-requests"
  "wl-clipboard"
  "xdotool"
  "pamixer"
  "gvfs"
  "jq"

#  -- Emoji --
  "noto-fonts-emoji"

#  -- Theming --
  "nwg-look"
  "qt5ct"
  "qt6ct"
  "qt5-wayland"
  "qt6-wayland"
  "kvantum"
  "kvantum-qt5"

#  -- Networking --
  "networkmanager"
  "network-manager-applet"
  "bluez"
  "bluez-utils"
  "blueman"

#  -- Streaming --
  "xdg-desktop-portal-hyprland"

#  -- Audio --
  "pavucontrol-qt"
  "ark"

#  -- Locking --
  "hypridle"
  "hyprlock"

#  -- Extra Applications for other rices --
  "fuzzel"
  "rofi-lbonn-wayland-git"
  "dunst"
  "udiskie"

#  -- Shell --
  "pokemon-colorscripts-git"
  "imagemagick"
  "wlr-randr"
  "fastfetch"
  "neovim"
  "btop"
  "grc"

  "eza"
  "fd"
  "bat"
)

SDDM_PACKAGES=(
# -- sddm and dependencies --
  "sddm"
  "qt5-quickcontrols2"
  "qt5-graphicaleffects"
  "qt5-svg"
)
