#!/bin/sh

# Set variables for script through rice configs
CURRENT_RICE=${1:-$(awk '/rice-current/ {print $NF}' "$HOME/.config/material/config")}
CURRENT_BG=${2:-$(cat ~/.config/swww/rices/${CURRENT_RICE} | awk -F ',' '{print $3}')} # make manual wallpapers possible
MODE=${3:-$(cat ~/.config/swww/rices/${CURRENT_RICE} | awk -F ',' '{print $2}')} # make manual wallpapers possible
CURRENT_ICONS="$(grep -m 2 "=" "${CONF_DIR}/gtk-3.0/settings.ini" | tail -n 1 | awk -F '=' '{print $2}')"
sed -i 's|^rice-current.*|rice-current = '${1}'|' ~/.config/material/config # set theme in config before using it as a variable in this script
sed -i 's|^system-theme.*|system-theme = '${MODE}'|' ~/.config/material/config # set theme in config before using it as a variable in this script
sed -i 's|wallpaper-current.*|wallpaper-current = '${CURRENT_BG}'|' ~/.config/material/config

# Launch into perltone if enabled
PERLTONE_STATUS=$(awk '/perltone-status/ {print $NF}' "$HOME/.config/material/config")
PERLTONE_OVERRIDE=${3:-$(cat ~/.config/swww/rices/${CURRENT_RICE} | awk -F ',' '{print $5}')} # make manual wallpapers possible

if [[ "$(echo $PERLTONE_STATUS | xargs)" == "on" || "$(echo $PERLTONE_OVERRIDE | xargs)" == "perltone=force" ]]; then
    sed -i 's|^perltone-status.*|perltone-status = on|' ~/.config/material/config # set forced perltone on before continuing
    WARNING_STATUS=$(awk '/perltone-warn-on-mono/ {print $NF}' $HOME/.config/material/config | xargs)
    if [[ "$WARNING_STATUS" == "on" && "$COLOR_PALETTE" == "mono" ]]; then 
        dunstify "Material" "Warning! Perltone on monochrome themes may not look good, consider disabling Perltone for them." --timeout=7001
    fi

    $HOME/.config/swww/scripts/change_theme_perltone &
    exit 127
fi

# Generated blurred background first since it takes a while
$HOME/.config/hypr/scripts/swww-wallpaper-blur "$CURRENT_RICE" "$CURRENT_BG" &

# Tmux
sed -i 's|^set -g status-bg.*|set -g status-bg '$([[ "$MODE" == "light" ]] && echo "white" || echo "black" )'|' $HOME/.tmux.conf

# Neovim
_NVIM_THEME="$CURRENT_RICE"
[[ "$CURRENT_RICE" == "Titanium-Mono" ]]                                            && _NVIM_THEME="monochrome"
[[ "$CURRENT_RICE" == "Gruvbox-Dark"  || "$CURRENT_RICE" == "Gruvbox-Light" ]]      && _NVIM_THEME="gruvbox"
[[ "$CURRENT_RICE" == "Solarized-Dark" || "$CURRENT_RICE" == "Solarized-Light" ]]   && _NVIM_THEME="solarized"  
[[ "$CURRENT_RICE" == "Nord" ]]                                                     && _NVIM_THEME="nord"
NVIM_THEME=$(echo $_NVIM_THEME | tr '[:upper:]' '[:lower:]')

sed -i 's|^vim.cmd.*|vim.cmd.colorscheme("'${NVIM_THEME}'")|' $HOME/.config/nvim/lua/core/plugins/colorscheme.lua
sed -i 's|^vim.opt.*|vim.opt.background = "'${MODE}'"|' $HOME/.config/nvim/lua/core/plugins/colorscheme.lua
# works only with my neovim dotfiles: https://github.com/POP303U/kickstart-nvim and these plugins:
#    'rose-pine/neovim',
#    'shaunsingh/solarized.nvim',
#    'catppuccin/nvim',
#    'fxn/vim-monochrome',
#    'shaunsingh/nord.nvim',
#    'ellisonleao/gruvbox.nvim',

# Dunst
sed -i 's|background.*|'"$(sed -n '1p' $HOME/.config/dunst/themes/${CURRENT_RICE})"'|' $HOME/.config/dunst/dunstrc
sed -i 's|foreground.*|'"$(sed -n '2p' $HOME/.config/dunst/themes/${CURRENT_RICE})"'|' $HOME/.config/dunst/dunstrc
sed -i 's|frame_color.*|'"$(sed -n '3p' $HOME/.config/dunst/themes/${CURRENT_RICE})"'|' $HOME/.config/dunst/dunstrc
pkill -x dunst
dunst & disown # reload

# Cava
for ((I=1; I<8; I++)); do
    sed -i 's|^gradient_color_'$I'.*|'"$(sed -n ''$I'p' $HOME/.config/cava/themes/${CURRENT_RICE})"'|' ~/.config/cava/config
done
pkill -SIGUSR2 cava

# Kvantum
kvantummanager --set ${CURRENT_RICE}

# qt5ct 
sed -i "s|^color_scheme_path=.*|color_scheme_path=$HOME/.config/qt5ct/colors/${CURRENT_RICE}.conf|" $HOME/.config/qt5ct/qt5ct.conf

# qt6ct
sed -i "s|^color_scheme_path=.*|color_scheme_path=$HOME/.config/qt6ct/colors/${CURRENT_RICE}.conf|" $HOME/.config/qt6ct/qt6ct.conf

# gtk2
ln -sf ~/.local/share/themes/${CURRENT_RICE}/gtk-2.0/gtkrc ~/.config/swww/gtkrc

# gtk3
sed -i 's|^gtk-theme-name.*|gtk-theme-name='${CURRENT_RICE}'|' ~/.config/gtk-3.0/settings.ini

# gtk4
rm -rf ~/.config/gtk-4.0
ln -s ~/.local/share/themes/${CURRENT_RICE}/gtk-4.0 ~/.config/gtk-4.0

# Reloading gtk changes
wait
~/.config/hypr/scripts/import-gsettings

# flatpak gtk
flatpak --user override --env=GTK_THEME="${CURRENT_RICE}" # flatpak gtk is not intended to work, and very hacky not all apps will work with this
flatpak --user override --env=ICON_THEME="${CURRENT_ICONS}"

# Kitty
ln -sf ~/.config/kitty/themes/${CURRENT_RICE}.conf ~/.config/kitty/themes/theme.conf 
pkill -SIGUSR1 kitty # reload

# Wlogout
ln -sf ~/.config/wlogout/themes/${CURRENT_RICE}.css ~/.config/wlogout/themes/theme.css

# Waybar
ln -sf ~/.config/waybar/themes/${CURRENT_RICE}.css ~/.config/waybar/themes/theme.css
~/.config/hypr/scripts/manage-waybar & # reload

# Fuzzel
ln -sf $HOME/.config/fuzzel/themes/${CURRENT_RICE}.ini $HOME/.config/fuzzel/fuzzel.ini

# Rofi
ln -sf $HOME/.config/rofi/themes/${CURRENT_RICE}.rasi $HOME/.config/rofi/themes/theme.rasi

# Wofi (hacky symlink to pywal path but who cares)
ln -sf $HOME/.config/wofi/themes/${CURRENT_RICE} $HOME/.cache/wal/colors 

# Hyprland
ln -sf ~/.config/hypr/themes/${CURRENT_RICE}.conf ~/.config/hypr/themes/theme.conf 

# Dolphin (just reloading)
ACTIVE_WORKSPACE=$(hyprctl -j activeworkspace | jq '.id')
if [ "$(hyprctl -j clients | jq --arg wid "$ACTIVE_WORKSPACE" '.[] | select(.workspace.id == ($wid | tonumber)) | select(.class == "org.kde.dolphin") | .mapped')" == "true" ] ; then
    pkill -x dolphin
    dolphin &
fi

# Swww
TRANSITION_TYPE=$(awk '/rice-transition/ {print $NF}' "$HOME/.config/material/config")

# you need dynamic `rose-pine-sddm` for this to work, check the installer for this option
cp -vrf ~/.config/swww/walls/${CURRENT_RICE}/${CURRENT_BG} /usr/share/sddm/themes/rose-pine-sddm/Backgrounds/current
swww img "$HOME/.config/swww/walls/${CURRENT_RICE}/$CURRENT_BG" \
    --transition-bezier .6,.94,.86,.23     \
    --transition-type "${TRANSITION_TYPE}" \
    --transition-duration 0.7              \
    --transition-fps 144                   \
    --invert-y                             \
    --transition-pos "2502, 1410"
