#!/bin/sh

function create_name() {
	NAME_FILE="$WALLPAPER_PATH/current/name"
	if [[ ! -f "$NAME_FILE" ]]; then
		touch "$NAME_FILE"
	fi

	# empty the file for new text
	echo -n > $NAME_FILE
	echo "$CURRENT_BG" > $NAME_FILE
}

DIR="${HOME}/.config/swww/walls"
WALLPAPER_PATH="/home/${USER}/.config/swww"
CURRENT_BG="$(find "$WALLPAPER_PATH" -name '*.jpg' -o -name '*.png' | shuf -n1)"

create_name


# Check if the program is running
if pgrep "swww-deamon" >/dev/null; then
	swww init
fi

#i dont know kekw: .16,.33,1,.46
#hyprdots:         .43,1.19,1,.4  https://github.com/prasanthrangan/hyprdots/blob/main/Configs/.config/hypr/scripts/swwwallpaper.sh
#ease-in-out:      .6,.94,.86,.23
#ease`ish:         .75,.47,.29,.83
swww img "$CURRENT_BG" \
    --transition-bezier .6,.94,.86,.23\
    --transition-type "grow" \
    --transition-duration 1 \
    --transition-fps 144 \
    --invert-y \
    --transition-pos "$( hyprctl cursorpos )"

### transition types:
#"none"
#"simple"
#"left"
#"right"
#"top"
#"bottom"
#"wipe"
#"grow"
#"center"
#"outer"
#"any"
#"wave"
#"random"
#"fade"
