#!/bin/sh

CURRENT_RICE=$(awk '/rice-current/ {print $NF}' $HOME/.config/material/config)
CURRENT_WALL=$(awk '/wallpaper-current/ {print $NF}' $HOME/.config/material/config)

swww init && swww img "$HOME/.config/swww/walls/$CURRENT_RICE/$CURRENT_WALL"
