#!/bin/sh

# Set up a log file for debugging
mkdir /tmp/material/null 

echo "--------------------------------------------
   Material Log File
--------------------------------------------

:: Current config:
$(cat $HOME/.config/material/config)

:: Start of logs $(date)
[$(dirname "$(realpath "$0")")::log] logging started..." > "/tmp/material/$(id -u)material-logfile.log"

# Patch wofi background-image path (using envsubst everywhere is not a good idea)
sed -i 's/\/home\/[^\/]*\//\/home\/'${USER}'\//g' ~/.config/wofi/style.css

CURRENT_SESSION="$(id -u)$DISPLAY$DESKTOP_SESSION$RANDOM$RANDOM$RANDOM"
touch "/tmp/material/$CURRENT_SESSION.session"
echo "Session started at: $(date)" >> "/tmp/material/$CURRENT_SESSION.session"
