#!/bin/sh

# Check if rofi is already running
if pgrep -x "rofi" >/dev/null; then
    pkill -x "rofi"
    exit 0
fi

# Source scaling variables
source ~/.config/hypr/scripts/globalvars

case "$1" in
    "rofi")
        # scale rofi before running
        rofi -show drun -config ~/.config/rofi/config.rasi -theme-str "${FONT_OVERRIDE_ROFI}" -theme-str "${BORDER_OVERRIDE_ROFI}"
        ;;
    "wallpaper")
        ~/.config/rofi/scripts/rofi-wallpaper
        ;;
    "emoji")
        ~/.config/rofi/scripts/rofi-emoji
        ;;
    "rice")
        ~/.config/rofi/scripts/rofi-rice-selector
        ;;
    "manager")
        ~/.config/rofi/scripts/rofi-manager main "${FONT_OVERRIDE}"
        ;;
    "waybar")
        ~/.config/rofi/scripts/rofi-waybar-selector
        ;;
    "cliphist")
        cliphist list | rofi -config ~/.config/rofi/clipboard.rasi -dmenu -theme-str "${FONT_OVERRIDE_ROFI}" -theme-str "${BORDER_OVERRIDE_ROFI}" -p "~ Material clipboard selection ~ " -i | cliphist decode | wl-copy
        ;;
    *)
        echo "Invalid choice $1"
        pkill -x "$LAUNCHER"
        ;;
esac
