#!/bin/sh
set -euo pipefail

RESOLUTION=$(echo "$(hyprctl -j monitors | jq .[].width),$(hyprctl -j monitors | jq .[].height)" )
TRANSITION_TYPE="$(awk '/rice-transition/ {print $NF}' ~/.config/material/config)"

# Set sddm wallpaper too  
CURRENT_RICE=$1
WALLPAPER=$2
WALLPAPER_PATH="$HOME/.config/swww/walls/$CURRENT_RICE/$WALLPAPER"

sed -i 's|wallpaper-current.*|wallpaper-current = '$WALLPAPER'|' ~/.config/material/config
PERLTONE_STATUS=$(awk '/perltone-status/ {print $NF}' "$HOME/.config/material/config")
PERLTONE_OVERRIDE=$(cat ~/.config/swww/rices/${CURRENT_RICE} | awk -F 'perltone =' '{print $2}')
if [[ "$(echo $PERLTONE_OVERRIDE | xargs)" != "force-disable" ]]; then
    if [[ "$(echo $PERLTONE_STATUS | xargs)" == "on" ]]; then
        ~/.config/hypr/scripts/swww-theme-perltone 
        exit 0
    fi
fi
~/.config/hypr/scripts/swww-wallpaper-blur "$CURRENT_RICE" "$WALLPAPER" &

cp -vrf ${WALLPAPER_PATH} /usr/share/sddm/themes/rose-pine-sddm/Backgrounds/current
swww img ${WALLPAPER_PATH}                 \
    --transition-bezier .6,.94,.86,.23     \
    --transition-type grow                 \
    --transition-duration 0.6              \
    --transition-fps 144                   \
    --invert-y                             \
    --transition-pos "$(hyprctl cursorpos)"
