#!/bin/sh

set -x

CURRENT_RICE=$(awk '/rice-current/ {print $NF}' $HOME/.config/material/config)
CURRENT_BG=$(awk '/wallpaper-current/ {print $NF}' $HOME/.config/material/config)

MATERIAL="$HOME/.config/material"   
WALLPAPER="$HOME/.config/swww/walls/$CURRENT_RICE/$CURRENT_BG"
PERLTONE="$HOME/.config/hypr/scripts/perltone"
PERLTONE_TEMPLATE="$HOME/.config/hypr/scripts/perltone-template"
COLOR_SCHEME="--$(awk '/system-theme/ {print $NF}' ~/.config/swww/rices/${CURRENT_RICE})"

COLOR_MODULATION="--$(awk '/perltone-colors/ {print $NF}' $HOME/.config/material/config)"
PERLTONE_BACKEND="--$(awk '/perltone-backend/ {print $NF}' $HOME/.config/material/config)"

# Ignore: Debugging
echo -e "DEBUG:\n----------------------\n\nCURRENT_RICE: $CURRENT_RICE\nCURRENT_BG: $CURRENT_BG\nWALLPAPER: $WALLPAPER\nCOLOR_SCHEME: $COLOR_SCHEME\nPERLTONE_BACKEND: $PERLTONE_BACKEND\nCOLOR_MODULATION: $COLOR_MODULATION\n\n----------------------"

# Generate colors
if [ ! -e "${HOME}/.cache/material/perltone/${CURRENT_RICE}/${CURRENT_BG}.colors" ]; then
    [ ! -e "${HOME}/.cache/material/perltone/${CURRENT_RICE}" ] && mkdir "${HOME}/.cache/material/perltone/${CURRENT_RICE}"
    ~/.config/hypr/scripts/perltone $WALLPAPER $COLOR_SCHEME $PERLTONE_BACKEND > "${HOME}/.cache/material/perltone/${CURRENT_RICE}/${CURRENT_BG}.colors"
    if [ $? -eq 1 ]; then
        echo "Error: Perltone couldn't generate colors."
        exit 1
    fi
fi

ln -sf "$HOME/.cache/material/perltone/${CURRENT_RICE}/${CURRENT_BG}.colors" $HOME/.config/material/colors/colors

# Generated blurred background first since it takes a while
~/.config/hypr/scripts/swww-wallpaper-blur "$CURRENT_RICE" "$CURRENT_BG" &

# Define the list of template files and their corresponding output paths
# Formatting:     input.template       :      output.template
TEMPLATES=(
    "$MATERIAL/templates/dunst.template:$HOME/.config/dunst/themes/Perltone"
    "$MATERIAL/templates/hypr.template:$HOME/.config/hypr/themes/Perltone.conf"
    "$MATERIAL/templates/fuzzel.template:$HOME/.config/fuzzel/themes/Perltone.ini"
    "$MATERIAL/templates/rofi.template:$HOME/.config/rofi/themes/Perltone.rasi"
    "$MATERIAL/templates/wofi.template:$HOME/.config/wofi/themes/Perltone"
    "$MATERIAL/templates/kitty.template:$HOME/.config/kitty/themes/Perltone.conf"
    "$MATERIAL/templates/foot.template:$HOME/.config/foot/themes/Perltone.ini"
    "$MATERIAL/templates/waybar.template:$HOME/.config/waybar/themes/Perltone.css"
    "$MATERIAL/templates/wlogout.template:$HOME/.config/wlogout/themes/Perltone.css"
    "$MATERIAL/templates/tty.template:$HOME/.bin/colors/Perltone"
    "$MATERIAL/templates/cava.template:$HOME/.config/cava/themes/Perltone"
    "$MATERIAL/templates/qt/qt5ct.template:$HOME/.config/qt5ct/colors/Perltone.conf"
    "$MATERIAL/templates/qt/qt6ct.template:$HOME/.config/qt6ct/colors/Perltone.conf"
    "$MATERIAL/templates/qt/perltone-kvconfig.template:$HOME/.config/Kvantum/Perltone/Perltone.kvconfig"
    "$MATERIAL/templates/qt/perltone-svg.template:$HOME/.config/Kvantum/Perltone/Perltone.svg"
    "$MATERIAL/templates/spotify.template:$HOME/.config/spicetify/Themes/Perltone/color.ini"
    "$MATERIAL/templates/sddm.template:/usr/share/sddm/themes/rose-pine-sddm/theme.conf"
    "$MATERIAL/templates/gtk/gtk4.template:$HOME/.local/share/themes/Perltone/gtk-4.0/gtk.css"
    "$MATERIAL/templates/gtk/gtk3.template:$HOME/.local/share/themes/Perltone/gtk-3.0/colors.css"
    "$MATERIAL/templates/discord.template:$HOME/.config/vesktop/themes/Perltone.css"
)

# Iterate over the list and generate color themes
for TEMPLATE in "${TEMPLATES[@]}"; do
    IFS=':' read -r -a PATHS <<< "$TEMPLATE"
    $PERLTONE_TEMPLATE "$MATERIAL/colors/colors" "${PATHS[0]}" "${PATHS[1]}"
done

# Make sure the script is executable
chmod +x "$HOME/.bin/colors/Perltone"

# tty 
$HOME/.bin/colors/Perltone

# Tmux (just uses tty colors)
sed -i 's|^set -g status-bg.*|set -g status-bg '$([[ "$MODE" == "light" ]] && echo "white" || echo "black" )'|' $HOME/.tmux.conf

# Cava
for ((I=1; I<=8; I++)); do
    sed -i 's|^gradient_color_'$I'.*|'"$(sed -n ''$I'p' $HOME/.config/cava/themes/Perltone)"'|' ~/.config/cava/config
done
pkill -SIGUSR2 cava

# Dunst
sed -i 's|background.*|'"$(sed -n '1p' $HOME/.config/dunst/themes/Perltone)"'|' $HOME/.config/dunst/dunstrc
sed -i 's|foreground.*|'"$(sed -n '2p' $HOME/.config/dunst/themes/Perltone)"'|' $HOME/.config/dunst/dunstrc
sed -i 's|frame_color.*|'"$(sed -n '3p' $HOME/.config/dunst/themes/Perltone)"'|' $HOME/.config/dunst/dunstrc
pkill -x dunst; dunst & disown # reload

# Kvantum
kvantummanager --set Perltone &

# qt5ct 
sed -i "s|^color_scheme_path=.*|color_scheme_path=$HOME/.config/qt5ct/colors/Perltone.conf|" $HOME/.config/qt5ct/qt5ct.conf
sed -i "s|^icon_theme=.*|icon_theme=Tela-circle-grey|" $HOME/.config/qt5ct/qt5ct.conf

# qt6ct
sed -i "s|^color_scheme_path=.*|color_scheme_path=$HOME/.config/qt6ct/colors/Perltone.conf|" $HOME/.config/qt6ct/qt6ct.conf
sed -i "s|^icon_theme=.*|icon_theme=Tela-circle-grey|" $HOME/.config/qt6ct/qt6ct.conf

# Hyprland
ln -sf ~/.config/hypr/themes/Perltone.conf ~/.config/hypr/themes/theme.conf 

# Fuzzel
ln -sf $HOME/.config/fuzzel/themes/Perltone.ini $HOME/.config/fuzzel/fuzzel.ini

# Rofi
ln -sf $HOME/.config/rofi/themes/Perltone.rasi $HOME/.config/rofi/themes/theme.rasi

# gtk3
sed -i 's|^gtk-theme-name.*|gtk-theme-name=Perltone|' ~/.config/gtk-3.0/settings.ini

# gtk4
rm -rf ~/.config/gtk-4.0
ln -s ~/.local/share/themes/Perltone/gtk-4.0 ~/.config/gtk-4.0

# Wofi (hacky symlink to pywal path but who cares)
ln -sf $HOME/.config/wofi/themes/Perltone $HOME/.cache/wal/colors 

# Spotify (spicetify)
spicetify apply &

# Kitty
ln -sf ~/.config/kitty/themes/Perltone.conf ~/.config/kitty/themes/theme.conf 
pkill -SIGUSR1 kitty # reload

# Kitty
ln -sf ~/.config/foot/themes/Perltone.ini ~/.config/foot/themes/theme.ini

# Wlogout
ln -sf ~/.config/wlogout/themes/Perltone.css ~/.config/wlogout/themes/theme.css

# Waybar
ln -sf ~/.config/waybar/themes/Perltone.css ~/.config/waybar/themes/theme.css
~/.config/hypr/scripts/manage-waybar & # reload

# Dolphin (just reloading)
ACTIVE_WORKSPACE=$(hyprctl -j activeworkspace | jq '.id')
if [ "$(hyprctl -j clients | jq --arg wid "$ACTIVE_WORKSPACE" '.[] | select(.workspace.id == ($wid | tonumber)) | select(.class == "org.kde.dolphin") | .mapped')" == "true" ] ; then
    pkill -x dolphin
    dolphin &
fi

# Swww
# you need dynamic `rose-pine-sddm` for this to work, check the installer for this option
TRANSITION_TYPE=$(awk '/rice-transition/ {print $NF}' "$HOME/.config/material/config")
CURRENT_RICE=$(awk '/rice-current/ {print $NF}' "$HOME/.config/material/config")

sed -i 's|wallpaper-current.*|wallpaper-current = '${CURRENT_BG}'|' ~/.config/material/config
cp -vrf $WALLPAPER /usr/share/sddm/themes/rose-pine-sddm/Backgrounds/current

swww img "$WALLPAPER" \
    --transition-bezier .6,.94,.86,.23     \
    --transition-type "${TRANSITION_TYPE}" \
    --transition-duration 0.7              \
    --transition-fps 144                   \
    --invert-y                             \
    --transition-pos "2502, 1410"

hyprctl reload
