#!/bin/sh

# Check if ImageMagick is installed
if ! [ -x "$(command -v convert)" ]; then
  echo 'Error: ImageMagick is not installed. Please install it to use this script.' >&2
  exit 1
fi

# Assigning arguments to variables
CURRENT_RICE="$1"
WALLPAPER="$2"
WALLPAPER_PATH="$HOME/.config/swww/walls/$CURRENT_RICE/$WALLPAPER"

CACHE_DIR="$HOME/.cache/material"

if [ ! -e "$CACHE_DIR/$CURRENT_RICE" ]; then
    mkdir -pv "$CACHE_DIR/$CURRENT_RICE"
fi

# Check if input image exists
if ! [ -f "$WALLPAPER_PATH" ]; then
  echo "Error: Input image '$WALLPAPER' not found."
  exit 1
fi

if file "$WALLPAPER_PATH" | grep -q GIF; then
    convert "$WALLPAPER_PATH"[0] "${CACHE_DIR}/${CURRENT_RICE}/${WALLPAPER}.temp.png"
else
    ln -sf "$WALLPAPER_PATH" "${CACHE_DIR}/${CURRENT_RICE}/${WALLPAPER}.temp.png"
fi

# Generate modified wallpapers, if they don't exist
[ ! -f "${CACHE_DIR}/${CURRENT_RICE}/${WALLPAPER}.thumb" ] && convert -strip -resize 1000 -gravity center -extent 1000 -quality 90 "${CACHE_DIR}/${CURRENT_RICE}/${WALLPAPER}.temp.png" "${CACHE_DIR}/${CURRENT_RICE}/${WALLPAPER}.thumb" &
wait

# Symlink to default directory
ln -sfv "$HOME/.config/swww/walls/$CURRENT_RICE/$WALLPAPER" "${HOME}/.config/swww/wallpaper"
ln -sfv "${CACHE_DIR}/${CURRENT_RICE}/${WALLPAPER}.thumb" "${HOME}/.config/swww/wallpaper.thumb"
ln -sfv "${CACHE_DIR}/${CURRENT_RICE}/${WALLPAPER}.temp.png" "${HOME}/.config/swww/wallpaper.hyprlock"
