#!/bin/sh

MATERIALGAMEMODE=$(awk '/hyprgamemode/ {print $NF}' "${HOME}/.config/material/config" | xargs)
if [[ ! "$MATERIALGAMEMODE" == "on" ]] ; then
    hyprctl --batch "\
        keyword animations:enabled 0;\
        keyword decoration:drop_shadow 0;\
        keyword decoration:blur:enabled 0;\
        keyword general:gaps_in 0;\
        keyword general:gaps_out 0;\
        keyword general:border_size 1;\
        keyword general:border_size 1;\
        keyword decoration:rounding 0"
    sed -i 's|hyprgamemode.*|hyprgamemode = on|' "${HOME}/.config/material/config"
    dunstify "Material" "Gamemode is enabled" --timeout=2500
    exit
else
    sed -i 's|hyprgamemode.*|hyprgamemode = off|' "${HOME}/.config/material/config"
    dunstify "Material" "Gamemode is disabled" --timeout=2500
fi

hyprctl reload
