#!/bin/sh

set -euox pipefail

BAR_STATE="$(awk '/bar-state/ {print $NF}' $HOME/.config/material/config)"

if [[ "$BAR_STATE" == "on" ]]; then
    sed -i 's|bar-state.*|bar-state = off|' ~/.config/material/config
    pkill -9 waybar
else 
    sed -i 's|bar-state.*|bar-state = on|' ~/.config/material/config
    ~/.config/hypr/scripts/manage-waybar &
fi
