#!/bin/sh

CURRENT_RICE=$(awk '/rice-current/ {print $NF}' "$HOME/.config/material/config")
PERLTONE_STATUS=$(awk '/perltone-status/ {print $NF}' "$HOME/.config/material/config")
PERLTONE_OVERRIDE=$(cat ~/.config/swww/rices/${CURRENT_RICE} | awk -F ',' '{print $5}')
if [[ "$(echo $PERLTONE_OVERRIDE | xargs)" == "perltone=force" ]]; then
    dunstify "Material" "Perltone can't be disabled on generic themes, please switch to a normal theme." --timeout=4500
    exit 1
fi

if [[ "$PERLTONE_STATUS" == "on" ]] ; then
    dunstify "Material" "Perltone is disabled" --timeout=2500
    sed -i 's|perltone-status.*|perltone-status = off|' $HOME/.config/material/config
else
    dunstify "Material" "Perltone is enabled" --timeout=2500
    sed -i 's|perltone-status.*|perltone-status = on|' $HOME/.config/material/config
fi

~/.config/hypr/scripts/load-config-material
