#!/bin/sh

sed -i 's|size =.*|size = 4| ' ~/.config/hypr/decoration.conf
sed -i 's|passes =.*|passes = 4|' ~/.config/hypr/decoration.conf
sed -i 's|blur-size.*|blur-size = 4|' ~/.config/material/config
sed -i 's|blur-passes.*|blur-passes = 4|' ~/.config/material/config
