#!/bin/sh
#
# Source scaling variables
source ~/.config/hypr/scripts/globalvars

[ ! -e $HOME/.config/hypr/resolutions ] && $HOME/.config/hypr/scripts/generate-resolutions
RESOLUTION=$(dir -1 $HOME/.config/hypr/resolutions | rofi -config ~/.config/rofi/config_no-icons.rasi -theme-str "${FONT_OVERRIDE_ROFI}" -theme-str "${BORDER_OVERRIDE_ROFI}" -dmenu -i -p "~ Load your preferred resolution ~")

[[ $RESOLUTION == "" ]] && exit 1

rm -v $HOME/.config/hypr/monitors.conf
touch $HOME/.config/hypr/monitors.conf

cat $HOME/.config/hypr/resolutions/$RESOLUTION > $HOME/.config/hypr/monitors.conf

hyprctl reload
wait
$HOME/.config/hypr/scripts/load-config-material
