#!/bin/sh
set -euo pipefail

LAUNCHER=$(awk -F '=' '/material-launcher/ {print $2}' $HOME/.config/material/config)
[[ $(echo $LAUNCHER | xargs) == "rofi" ]] && LAUNCHER="rofi -config ~/.config/rofi/config_no-icons.rasi -dmenu " || LAUNCHER="$LAUNCHER --dmenu" # patch for rofi

function change_rice() {
	CHANGE_RICE="/home/${USER}/.config/swww/scripts/change_theme"
	$CHANGE_RICE $RICE_FULL_NAME
}

# use --cache-file /dev/null to use predefined order
RICE_SEL_NAME=$(sed '/^### ENTRIES ###$/d' /home/${USER}/.config/swww/rices/#entries# | $LAUNCHER -i "~ Material rice selector ~ " ) 
RICE_FULL_NAME="$(echo $RICE_SEL_NAME | awk '{sub(/^[^ ]+ /, ""); print}' | xargs)"
RICE_FILE="/home/${USER}/.config/swww/rices/${RICE_FULL_NAME}"

if [[ ! -f "$RICE_FILE" ]]; then
    echo "Error: Rice file with the name '$RICE_FULL_NAME' not found in the specified directory."
    exit 1
fi

# save the config
change_rice
