#!/bin/sh
set -euox pipefail

# Source scaling variables
source ~/.config/hypr/scripts/globalvars

SWWW_DIR="/home/${USER}/.config/swww"
CURRENT_RICE="$(awk '/rice-current/ {print $NF}' /home/${USER}/.config/material/config)"
WALLPAPER_NAME=$(dir -1 /home/${USER}/.config/swww/walls/${CURRENT_RICE} | rofi -config ~/.config/rofi/config_no-icons.rasi -dmenu -theme-str "${FONT_OVERRIDE_ROFI}" -theme-str "${BORDER_OVERRIDE_ROFI}" -p "~ Material wallpaper selector ~ " -i)
WALLPAPER="/home/${USER}/.config/swww/walls/${CURRENT_RICE}/${WALLPAPER_NAME}"

if [[ ! -f "$WALLPAPER" ]]; then
    echo "Error: Wallpaper file with the name '$WALLPAPER_NAME' not found in the specified directory."
    exit 1
fi

# Set the wallpaper
CHANGE_WALLPAPER="${HOME}/.config/swww/scripts/change_wallpaper"
$CHANGE_WALLPAPER $CURRENT_RICE $WALLPAPER_NAME
